"""added last_update field in districts

Revision ID: 67b32ea392a8
Revises: 
Create Date: 2020-06-30 21:19:13.284880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b32ea392a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('districts', 'last_update')
    # ### end Alembic commands ###
